name: Get tools new versions
on:
  schedule:
    - cron: '0 8 * * THU'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  find-new-tool-versions:
    strategy:
      matrix:
        tool: [Xamarin, Python]
    name: Searching for new TOOL versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-new-TOOL-versions
        name: Get new TOOL versions
        run: echo "::set-output name=versions-output::$(./get-new-tool-versions/verify-new-tool-version-added-to-image.ps1 -ToolName ${{ matrix.tool }})"
      - name: Check Versions
        if: steps.get-new-TOOL-versions.outputs.versions-output == ''
        run: Write-Host "No new versions found"
      - uses: ./.github/actions/send-slack-notification
        if: steps.get-new-TOOL-versions.outputs.versions-output != ''
        with:
          url: 'This is url'
          tool-name: '${{ matrix.tool }}'
          tool-version: ${{ steps.get-new-TOOL-versions.outputs.versions-output }}
          image-url: 'https://avatars.githubusercontent.com/u/790012?s=200&v=4'
          add-to-toolset-flag: '-AddToToolsetFlag'

  check_build:
    name: Check build for failures 
    runs-on: ubuntu-latest
    needs: [find-new-tool-versions]
    if: failure()
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/send-slack-notification
        with:
          url: 'This is url'
          tool-name: 'Python or Xamarin'
          pipeline-url: '$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID'
          text: "The build of the Xamarin or Python detection pipeline has failed stages:"